name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/cache-wipe-linux-amd64
        GOOS=windows GOARCH=amd64 go build -o dist/cache-wipe-windows-amd64.exe
        GOOS=darwin GOARCH=amd64 go build -o dist/cache-wipe-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -o dist/cache-wipe-darwin-arm64
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        draft: false
        prerelease: false