name: Generate go.sum

on:
    workflow_dispatch: # Manual trigger

jobs:
    generate:
        name: Generate go.sum
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.21"

            - name: Download dependencies
              run: |
                  go mod download
                  go mod tidy

            - name: Upload go.sum
              uses: actions/upload-artifact@v4
              with:
                  name: go-sum-file
                  path: go.sum
